{
    "type": "bundle",
    "id": "bundle--e305ee95-77bc-44b1-9141-1bf7bca6dd25",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--16afa559-f28c-4b3d-b4c5-6de75dd2e00b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-31T00:42:42.502598Z",
            "modified": "2025-03-31T00:42:42.502598Z",
            "name": "CVE-2025-2953",
            "description": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-2953"
                }
            ]
        }
    ]
}