{
    "type": "bundle",
    "id": "bundle--5bdac3ec-3d1d-4833-aa95-87bea3e8a73b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--49510173-f715-4fca-b23f-627b190ef678",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-03T00:39:49.61757Z",
            "modified": "2025-04-03T00:39:49.61757Z",
            "name": "CVE-2025-2999",
            "description": "A vulnerability was found in PyTorch 2.6.0. It has been rated as critical. Affected by this issue is the function torch.nn.utils.rnn.unpack_sequence. The manipulation leads to memory corruption. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-2999"
                }
            ]
        }
    ]
}