{
    "type": "bundle",
    "id": "bundle--f809233b-4e2a-4908-9427-32d152bb4d9c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--3c98d848-a970-4f39-869d-956547861c6d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T00:39:47.383366Z",
            "modified": "2025-04-04T00:39:47.383366Z",
            "name": "CVE-2025-32051",
            "description": "A flaw was found in libsoup. The libsoup soup_uri_decode_data_uri() function may crash when processing malformed data URI. This flaw allows an attacker to cause a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32051"
                }
            ]
        }
    ]
}