{
    "type": "bundle",
    "id": "bundle--40623b02-7f59-4caa-b9d5-c57396df9bba",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--057c4b53-1598-46b7-a0bf-6d8621abaf04",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-04T00:39:47.384811Z",
            "modified": "2025-04-04T00:39:47.384811Z",
            "name": "CVE-2025-32049",
            "description": "A flaw was found in libsoup. The SoupWebsocketConnection may accept a large WebSocket message, which may cause libsoup to allocate memory and lead to a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32049"
                }
            ]
        }
    ]
}